### PR TITLE
#2 support for configuration added. Configuration is the starting poi…

### PR DESCRIPTION
**Pull request by satishthulva**
…nt to find out all available config. ConfigParser parses the config from file and returns. Configurate is used so that the underlying configuration file format can change without changing the parsing code, to certain extent.

@DoNotSpamPls : Please read the check-in comment and let me know if this sounds okay. I did not integrate the config with the project. Wherever you need this configuration, you can call `ConfigParser.parseConfig()`. This will return the full config. 

Please take a look at [Configurate](https://docs.spongepowered.org/stable/en/plugin/configuration/serialization.html) to understand how the code works.

If this looks fine, you can close the issue #2

### CODE REVIEW

**Comment by DoNotSpamPls** [comment]
Even though this PR is failing, I'm going to merge it - it seems to just be an issue with Java 9 and 10, which I won't be building for anyway (Java 11 being LTS)

Thank you very much for the PR, i'm going to be expanding it from now on 😛

**Comment by DoNotSpamPls** [comment]
Actually, @satishthulva, I've found a bit of an issue with your code - there is no code, as far as I can see, that puts the config in the /plugins/velocityutils/config.yaml file. Could you check on that please?

**Comment by satishthulva** [comment]
@DoNotSpamPls : I didn't copy the file contents to other file intentionally. Do you need it?

**Comment by DoNotSpamPls** [comment]
Yes, that's the way users can edit the config. Opening the JAR file and tinkering with it is not very user-friendly.

**Comment by satishthulva** [comment]
Oh, okay. I'll do that then, by end of day today. @DoNotSpamPls one question. The path of the directory where config file has to be copied, can I expect it to be an argument to the config provider? Or it is a well understood path can be hard-coded. For e.g. like you said, /plugins/velocityutils.

**Comment by DoNotSpamPls** [comment]
@satishthulva look at #2 for example code -> there is a config path in there which you can usr

**Comment by satishthulva** [comment]
@DoNotSpamPls Now, there is an option to take user specific config. Please take a look at the pull request.

**Pull request merged**
